ignore:
  - "webapp/e2e/**"
  - "webapp/public/**"
  - "webapp/loadtestexample/**"
  - "webapp/src/test/**"
  - "webapp/src/api/**"
  - "webapp/src/*.[tsx, ts, css]"
  - "webapp/server.ts"
  - "docs/**"
  - "data/**"
