version: '3.5'
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  restapi:
    build: ./restapi
    ports:
      - "5000:5000"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: SergioArroni
      MONGO_INITDB_ROOT_PASSWORD: julio321
      MONGO_INITDB_DATABASE: DeDesktop
    ports:
      - "27017:27017"